# Javascript Node CircleCI 2.0 configuration file
defaults: &defaults
    docker:
        # specify the version you desire here
        - image: circleci/node:8.6.0

      working_directory: ~/repo

version: 2
jobs:
    checkout:
        <<: *defaults
        steps:
            - checkout

            # Download and cache dependencies
            - restore_cache:
                keys:
                - v1-dependencies-{{ checksum "package.json" }}
                # fallback to using the latest cache if no exact match is found
                - v1-dependencies-

            - run:
                name: NPM Install
                command: npm install

            - save_cache:
                paths:
                  - node_modules
                key: v1-dependencies-{{ checksum "package.json" }}

    unit-test:
        <<: *defaults
        steps:
            - run:
                name: NPM Install
                command: npm install
            - run:
                name: Unit Test
                command: npm run test

    deploy:
        <<: *defaults
        steps:
            - run:
                name: Install Now CLI
                command: sudo npm install --global --unsafe-perm now
            - deploy:
                name: Deploy & Alias
                command: now -t dGa8L7SvVQn3vX6sxx7Xnlbj

workflows:
    version: 2
    test-deploy-purge:
        jobs:
            - checkout
            - unit-test:
                requires:
                    - checkout
            - deploy:
                requires:
                    - unit-test

